-- CreateTable
CREATE TABLE `posts` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `i18n` VARCHAR(191) NOT NULL DEFAULT 'zh-Hans',
    `slug` VARCHAR(191) NOT NULL,
    `layout` VARCHAR(191) NOT NULL DEFAULT 'Post',
    `category` VARCHAR(191) NOT NULL DEFAULT '博客',
    `categorySlug` VARCHAR(191) NOT NULL DEFAULT 'blog',
    `chapter` VARCHAR(191) NULL DEFAULT '',
    `title` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `scripts` VARCHAR(191) NOT NULL DEFAULT '',
    `headings` VARCHAR(191) NOT NULL DEFAULT '[]',
    `content` VARCHAR(191) NULL,
    `readMins` DOUBLE NOT NULL DEFAULT 0,
    `words` INTEGER NOT NULL DEFAULT 0,
    `author` VARCHAR(191) NOT NULL DEFAULT 'Tsuizen',
    `tags` VARCHAR(191) NULL,
    `featureImage` VARCHAR(191) NOT NULL,
    `featureImageWidth` INTEGER NOT NULL DEFAULT 0,
    `featureImageHeight` INTEGER NOT NULL DEFAULT 0,
    `featureVideo` VARCHAR(191) NULL DEFAULT '',
    `demoLink` VARCHAR(191) NULL DEFAULT '',
    `sourceLink` VARCHAR(191) NULL DEFAULT '',
    `filename` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `kp_slug`(`slug`, `i18n`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
